CREATE SCHEMA STEAMFM;

CREATE TABLE STEAMFM.GENERO_JOGO (
ID_GENERO_JOGO INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME_GENERO VARCHAR(100) NOT NULL
);

INSERT INTO STEAMFM.GENERO_JOGO (NOME_GENERO) VALUES ('2D'),
('Ação'),
('Ação / Aventura'),
('Alta Rejogabilidade'),
('Anime'),
('Arcade'),
('Atmosferico'),
('Aventura'),
('Baseado em Equipes'),
('Basquete'),
('Beat''em Up'),
('Câmera Topo-Baixo'),
('Cartunizado'),
('Casual'),
('Clássico'),
('Clique Clique'),
('Comédia'),
('Competitivo'),
('Controle por Toque'),
('Cooperativo'),
('Cooperativo Local'),
('Cooperativo Online'),
('Corrida'),
('Cyberpunk'),
('Dark Humor'),
('Desenhado à mão'),
('Desenvolvimento de Jogos'),
('Design e ilustração'),
('Difícil'),
('Educativo'),
('Em Turnos'),
('Engraçado'),
('Escolha a Sua Aventura'),
('Escolhas Importam'),
('Espacial'),
('Esportes'),
('Estilizado'),
('Estratégia'),
('Estratégia em Tempo Real (RTS)'),
('Estratégia em turnos'),
('Exploração'),
('Fabricação'),
('Fantasia'),
('Fantasia Sombria'),
('Ficção científica'),
('Física'),
('fofo'),
('FPS'),
('Furtivo'),
('Game Maker'),
('genero'),
('Gráficos Pixelados'),
('Gratuito para Jogar'),
('Hack and Slash'),
('Hackear'),
('Hardware'),
('Hidden Object'),
('História'),
('História Alternativa'),
('Indie'),
('Infantil'),
('Jogador Deus'),
('Jogador x Inimigo (PvE)'),
('Jogador x Jogador (PvP)'),
('Jogo de Ação Focado em Perso'),
('J-RPG'),
('Kickstarter'),
('Local para 4 Jogadores'),
('Máquina Steam'),
('Mecha'),
('Medieval'),
('Metroidvania'),
('Multijogador'),
('Multijogador Local'),
('Multijogador Massivo Online (MMO)'),
('Mundo Aberto'),
('Mystery Dungeon'),
('Ninja'),
('Nudez'),
('Oficina de jogos'),
('Parkour'),
('Personalização de Armas'),
('Personalização de Personagens'),
('Plataforma'),
('Plataforma com Quebra-cabeças'),
('Point-and-Click'),
('Primeira Pessoa'),
('Produção de áudio'),
('Produção de vídeo'),
('Protagonista feminina'),
('Publicação para web'),
('Puzzle'),
('Quadrinhos'),
('Quick-Time Events'),
('Remake'),
('Rico em História'),
('Roguelike'),
('Romance Visual'),
('RPG'),
('RPG de Ação'),
('RPG Maker'),
('sandbox'),
('Sangue'),
('Saquear'),
('SHMUP com visão de cima'),
('SHMUP de controle duplo'),
('Shoot ''em up (shmup)'),
('Simulação'),
('Sobrevivência'),
('software'),
('Software de treinamento'),
('Sombrio'),
('Soundtrack'),
('Star Wars'),
('Steampunk'),
('Super Herói'),
('Tanques'),
('Terceira Pessoa'),
('Terror'),
('Terror de Sobrevivência'),
('Tiro'),
('Tower Defense'),
('TrackIR'),
('trilha sonora boa'),
('Um jogador'),
('Utilitários'),
('Wargame'),
('Warhammer 40K'),
('Xadrez'),
('Zumbi');

CREATE TABLE STEAMFM.MUSICA (
ID_MUSICA INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITULO_MUSICA VARCHAR(100) NOT NULL,
ID_MUSICA_LASTFM INT NOT NULL
);

CREATE TABLE STEAMFM.ALBUM (
ID_ALBUM INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TITULO_ALBUM VARCHAR(100) NOT NULL,
ID_ALBUM_LASTFM INT NOT NULL
);

CREATE TABLE STEAMFM.ARTISTA (
ID_ARTISTA INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME_ARTISTA VARCHAR(100) NOT NULL,
ID_ARTISTA_LASTFM INT NOT NULL
);

CREATE TABLE STEAMFM.RELACAO (
ID_RELACAO INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ID_GENERO_JOGO INT, FOREIGN KEY (ID_GENERO_JOGO) REFERENCES STEAMFM.GENERO_JOGO (ID_GENERO_JOGO) ON DELETE CASCADE,
ID_MUSICA INT, FOREIGN KEY (ID_MUSICA) REFERENCES STEAMFM.MUSICA (ID_MUSICA) ON DELETE CASCADE,
ID_ALBUM INT, FOREIGN KEY (ID_ALBUM) REFERENCES STEAMFM.ALBUM (ID_ALBUM) ON DELETE CASCADE,
ID_ARTISTA INT, FOREIGN KEY (ID_ARTISTA) REFERENCES STEAMFM.ARTISTA (ID_ARTISTA) ON DELETE CASCADE
);
 
--INSERT INTO STEAMFM.RELACAO(ID_GENERO_JOGO, ID_MUSICA, ID_ALBUM, ID_ARTISTA) VALUES (),();
